### ISSUE TITLE
Docs - update link anchors

### ISSUE THREAD

**Issue by intelliot** [ripple/ripple-lib#1175]
https://github.com/ripple/xrpl-dev-portal/pull/760#issuecomment-574288812

Guessing that is caused by https://github.com/ripple/ripple-lib/pull/1153

**Comment by FKSRipple** [comment]
Hmm, it looks like `doctoc` is combining these markdown files in an unexpected way and removing important whitespace between the table and the next header:

<img width="638" alt="Screen Shot 2020-01-16 at 8 30 53 AM" src="https://user-images.githubusercontent.com/56697533/72543415-88a51400-383a-11ea-8ede-059a7bba4b3d.png">

This is strange though, because there's an extra new-line in the file containing the table, which seems to be getting stripped out. I'm not familiar with this library though, @intelliot any idea what may be going on?

**Comment by mDuo13** [comment]
I doubt it's `doctoc` specifically but more likely `ejs` that's stripping extra whitespace around its includes. In most cases the stripped whitespace is extraneous but in this one case it's necessary to separate the end of the table from the start of the heading.

(I think doctoc just finds headers and makes a list of them, so it's plausible that it's facing the same problem Dactyl's parser is.)

**Comment by intelliot** [comment]
Should be fixed in 1.6.2
