### ISSUE TITLE
destination tag in ripple account 

### ISSUE THREAD

**Issue by samanyousefi** [ripple/ripple-lib#1314]
hi, I used from the ripple-lib module and I created some wallet and transaction but I need a tag (i think its destination tag) for using in the Binance web site, in my created wallet I have four properties : 
{
  xAddress: 'X7XJbXTjLarHAbqdcx43MmKYJxMF7X67fnxZn921iQdv2Lf',
  secret: 'ssxnUV5nXu2c5ZHiviAztEwGA94xJ',
  classicAddress: 'rp9qJLxqXurfofNxQFX6cDDjAbEQNVTakv',
  address: 'rp9qJLxqXurfofNxQFX6cDDjAbEQNVTakv'
}

how I can get the tag of this account.

**Comment by intelliot** [comment]
If this is a new account that you have full custody of, then there is no destination tag. The destination tag is an arbitrary number that you can use to help identify the payment in your payment history. So if you control the entire account, you can enter/use any destination tag you want. Like all XRPL tags, it must be a 32-bit unsigned integer. 

Note that the 'secret' is all that's needed to control a new account. Since your secret has been publicly posted above, do NOT use this particular account. Generate a new one.
