### ISSUE TITLE
Ripple Address check

### ISSUE THREAD

**Issue by vhpoet** [ripple/ripple-lib#508]
This should fail 
```
transaction.payment('rUukJnRRt1PH1wiADeMQYaZc9GJaRo1vbg','d4704546ca7432f24679849266ae53b70185d23c',100)
```

`d4704546ca7432f24679849266ae53b70185d23c` is not a ripple address.

**Comment by sublimator** [comment]
It's 20 bytes as hex, and when encoded it's: `rL4Gk4HDr9AH2reogMbgQaE2cMYxvCUy23`

A real account: https://wisepass.com/ripple/rL4Gk4HDr9AH2reogMbgQaE2cMYxvCUy23

I think it's because UInt160 is used to parse `TakerGetsIssuer` etc  where hex is used. 

I guess payment() could be updated to force usage of base58 encoded addresses or a UInt160 ?

How did this bite you?

**Comment by clark800** [comment]
@vhpoet This seems to be intended behavior, so I'm not sure if it's a good idea to change it: https://github.com/ripple/ripple-lib/blob/develop/src/core/uint160.js#L54

Should we close this?

**Comment by vhpoet** [comment]
@clark800 ok, let's close this for now.
