### ISSUE TITLE
Ripple-lib with react native

### ISSUE THREAD

**Issue by Kishanjvaghela** [ripple/ripple-lib#775]
Can I use this lib with react native?

**Comment by intelliot** [comment]
Yes.

**Comment by emilbaekdahl** [comment]
How so? I have built the single JS file according to the [instructions](https://ripple.com/build/rippleapi-beginners-guide/#build-instructions) but I get `_ is not defined` even though I import `lodash` before `ripple-lib` - like so
```
import _ from 'lodash'
import '../lib/ripple-0.17.9'
```
How is this done properly, @intelliot ?

**Comment by allmaxgit** [comment]
I have *Super expression must either be null or a function, not object* error.

**Comment by astone123** [comment]
I'm having trouble importing this library into my React Native project. I'm getting an error that `node_modules/ripple-lib/dist/api.js` is trying to require a module called "event" that does not exist in the module map.

This is how I'm importing
`import { RippleAPI } from 'ripple-lib';`

Not sure if this is a React Native issue or an issue with this library. Is anyone else having this problem?

**Comment by FredKSchott** [comment]
I'm not familiar enough with react-native to debug this too deeply, but it looks like Node.js/NPM packages aren't completely plug-and-play on react-native. For example, `"events" module not found` is because "events" is a Node.js core module, so it makes sense that this would fail when run outside of Node.

It would be great if someone with more react-native experience could give some guidance here. For example, should this be solved via:
- React Native Bundler / https://gist.github.com/parshap/e3063d9bf6058041b34b26b7166fd6bd
- Publishing uncompiled source so that react-native tooling can better handle?
- Use the bundled browser version in `build/`?
- Move from node core modules like "events" to userland packages like "event-emitter"?

**Comment by mszczech01** [comment]
> I'm having trouble importing this library into my React Native project. I'm getting an error that `node_modules/ripple-lib/dist/api.js` is trying to require a module called "event" that does not exist in the module map.
> 
> This is how I'm importing
> `import { RippleAPI } from 'ripple-lib';`
> 
> Not sure if this is a React Native issue or an issue with this library. Is anyone else having this problem?

I'm experiencing this issue as well. Have you managed to find a work around?

**Comment by reneveyj** [comment]
After hours of research and testing I found a way to integrate ripple-lib in React Native and created a boilerplate project with a demo and a description of the steps I took to make it work:
[https://github.com/reneveyj/RNRippleLib](https://github.com/reneveyj/RNRippleLib)

**Comment by elmurci** [comment]
FYI - I have created a PR https://github.com/ripple/ripple-lib/pull/1341 to update instructions on how to use `ripple-lib` with `React Native`.

**Comment by intelliot** [comment]
Fixed by #1387. Instructions are in the README.
