### ISSUE TITLE
How to empty ripple balance 

### ISSUE THREAD

**Issue by thomsonimjd** [ripple/ripple-lib#899]
I have a riplle account which has 10000 xrp which I would like to empty the wallet, in the sense want transfer all the balance to another account. So currenty the transaction fee is 0.000012, (total balance - transaction fee), so I have to send the remaining amount, the the account would have 0 xpr right. 

I tried this, I could not empty the account.  Please let me know any other chances to work on this.

**Comment by intelliot** [comment]
The account cannot be emptied to 0 XRP due to the [reserve requirement](https://developers.ripple.com/reserves.html). If your account does not own any objects (such as offers), then the current minimum reserve requirement is 20 XRP.

So in your case, you should be able to send up to 9980 XRP minus fees.
