### ISSUE TITLE
Address format including destination tag

### ISSUE THREAD

**Issue by intelliot** [ripple/ripple-lib#904]
For exchanges and hosted wallets, it would be useful to have a "packed" address format that includes and encodes the destination tag.

See https://github.com/ripple/ripple-address-codec/issues/7

**Comment by MarkusTeufelberger** [comment]
There used to be this: https://wiki.ripple.com/Ripple_URIs

**Comment by sublimator** [comment]
Nail it up and get the money!

**Comment by MarkusTeufelberger** [comment]
What money?

**Comment by sublimator** [comment]
It's an expression from the building industry. Quit the hand wringing and just get it done type thing ... Nail it up and get the money!

**Comment by sublimator** [comment]
I was helping a guy who sent to a gateway with a destination tag with a single trailing digit wrong in  a September 2018 transaction ... 

Upon looking at around one and half million XRP payment transactions, yet without knowing for sure, it looks like the gateway has received millions of ill gotten XRP due to messed up destination tags ... 

That's tragic ... 

You'd be amazed at the amount of varying length slices of 123456 there was ...

**Comment by sublimator** [comment]
@intelliot

**Comment by intelliot** [comment]
Don’t people notice fairly quickly when they aren’t credited for their deposit?

We’ll suggest a new packed address format, though it’ll likely be a while before people actually adopt it.

**Comment by nfcpasses** [comment]
In this case the funds became in dispute

**Comment by mDuo13** [comment]
https://github.com/xrp-community/standards-drafts/issues/6 is a proposal for this

**Comment by intelliot** [comment]
This need is met by [the X-address format (supported by ripple-address-codec)](https://github.com/ripple/ripple-address-codec).
