### ISSUE TITLE
{ BigNumber Error: new BigNumber() not a number: undefined

### ISSUE THREAD

**Issue by dkemper01** [ripple/ripple-lib#975]
I am using the following code to locally sign a payment.  The result of the sign method invoke yields: 

{ BigNumber Error: new BigNumber() not a number: undefined
    at raise (/Users/Dan/Documents/PoC/ripple-test/node_modules/bignumber.js/bignumber.js:1190:25)
    at /Users/Dan/Documents/PoC/ripple-test/node_modules/bignumber.js/bignumber.js:1178:33
    at new BigNumber (/Users/Dan/Documents/PoC/ripple-test/node_modules/bignumber.js/bignumber.js:193:67)
    at signWithKeypair (/Users/Dan/Documents/PoC/ripple-test/node_modules/ripple-lib/src/transaction/sign.ts:35:15)
    at RippleAPI.sign (/Users/Dan/Documents/PoC/ripple-test/node_modules/ripple-lib/src/transaction/sign.ts:75:12)
    at signPayment (/Users/Dan/Documents/PoC/ripple-test/get-account-info.js:110:14)
    at /Users/Dan/Documents/PoC/ripple-test/get-account-info.js:53:10
    at <anonymous> name: 'BigNumber Error' }

```
const secret = 'sn9x3fyK7rYzp5rSeCsuRrxcPdpTP';

function signPayment(api) {
  let txPayment = {
    "source": {
      "address": "r9cZA1mLK5R5Am25ArfXFmqgNwjZgnfk59",
      "amount": {
        "value": 1.000000000,
        "currency": "XRP",
        "counterparty": "rMH4UxPrbuMa1spCBR98hLLyNJp4d8p4tM"
      }
    },
    "destination": {
      "address": "rpZc4mVfWUif9CRoHRKKcmhu1nx2xktxBo",
      "amount": {
        "value": 1.000000000,
        "currency": "XRP",
        "counterparty": "rMH4UxPrbuMa1spCBR98hLLyNJp4d8p4tM"
      }
    }
  };

  return api.sign(JSON.stringify(txPayment), secret);
}
```

**Comment by intelliot** [comment]
@dkemper01 There are several problems:

1. A transaction must have a few other fields before you can sign it. Particularly: `fee` and `sequence`. Also, `maxLedgerVersion` (`LastLedgerSequence` in the `rippled` API) is recommended in most cases.
2. The first parameter of `sign` must be in `rippled` `txJSON` format. Here's an example of how that looks:
```javascript
"{\"TransactionType\":\"Payment\",\"Account\":\"r9cZA1mLK5R5Am25ArfXFmqgNwjZgnfk59\",\"Destination\":\"rpZc4mVfWUif9CRoHRKKcmhu1nx2xktxBo\",\"Amount\":\"1000000\",\"Flags\":2147483648,\"LastLedgerSequence\":14721478,\"Fee\":\"12\",\"Sequence\":1}"
```
3. You can use `preparePayment` to generate `rippled` `txJSON`. There are two ways to do this: online and offline. How are you initializing your `api` object? If you specify `server` and call `connect()`, then you are online.

### Online payment preparation

- Call `connect()` and wait until RippleAPI is connected (use `await` or `then`).
- Note that `preparePayment` is always asynchronous and returns a Promise.
- If you do not specify `fee`, `sequence`, or `maxLedgerVersion`, they will be filled in automatically.

### Offline payment preparation

- Initialize `RippleAPI` with no `server` option.
- You *must* specify the `fee`, `sequence`, and `maxLedgerVersion` parameters.
- See [Offline functionality](https://developers.ripple.com/rippleapi-reference.html#offline-functionality) for details.

### Working example
```javascript
const RippleAPI = require('ripple-lib').RippleAPI;
const api = new RippleAPI({server: 'wss://s.altnet.rippletest.net:51233'});

// online - connect() before calling preparePayment
api.connect().then(async () => {

  const secret = 'sn9x3fyK7rYzp5rSeCsuRrxcPdpTP';

  async function signPayment(api) {
    let txPayment = {
      "source": {
        "address": "r9cZA1mLK5R5Am25ArfXFmqgNwjZgnfk59",
        "maxAmount": { // should use `maxAmount` instead of `amount` here
          "value": "1.000000", // should be a string
          "currency": "XRP" // no counterparty for XRP
        }
      },
      "destination": {
        "address": "rpZc4mVfWUif9CRoHRKKcmhu1nx2xktxBo",
        "amount": {
          "value": "1.000000",
          "currency": "XRP"
        }
      }
    };

    // first parameter should match `source.address`
    const payment = await api.preparePayment("r9cZA1mLK5R5Am25ArfXFmqgNwjZgnfk59", txPayment)
    return api.sign(payment.txJSON, secret);
  }

  console.log(await signPayment(api))
})
```

Note that since your secret has been revealed, this account should not be used outside of the test net.

For a more complete example, see the [RippleAPI Beginners Guide](https://developers.ripple.com/get-started-with-rippleapi-for-javascript.html).

**Comment by dkemper01** [comment]
This is very helpful, thank you.  I've got it sorted now.

**Comment by intelliot** [comment]
You're welcome!

Once you've finished building something, feel free to add it to our new [list of applications](https://github.com/ripple/ripple-lib/blob/develop/APPLICATIONS.md) that use ripple-lib :)
