### ISSUE TITLE
Clean up the "combine" method

### ISSUE THREAD

**Issue by intelliot** [ripple/ripple-lib#987]
The "combine" method has a TODO and should be cleaned up or refactored.

**Comment by Soolan** [comment]
Hi @intelliot, 
if I understand correctly combine needs to decode the signed transactions so it can validate the payment transaction (line 24-29 in combine.ts):
```
  const txs: any[] = _.map(signedTransactions, binary.decode)
  const tx = _.omit(txs[0], 'Signers')
  if (!_.every(txs, _tx => _.isEqual(tx, _.omit(_tx, 'Signers')))) {
    throw new utils.common.errors.ValidationError(
      'txJSON is not the same for all signedTransactions')
  }
```
That block can be extracted from combine() and put into a new validation method but other than that, I think the combine() method needs to take array of strings and convert them to objects, because at the end it needs to return the hash string (and id) using the encode() method.

I think if we refactor this method and take away decode/encode methods, then we have to slice and concatenate transaction strings directly. I'm not sure if this is a practical idea.

Please let me know if I'm missing something here.

**Comment by intelliot** [comment]
That sounds correct. I don't think we need to "take away" any methods, but it would be good to rewrite them for clarity. It would also be good to reduce the dependence on lodash, replacing those calls with native JS methods, or our own implementations.

**Comment by Soolan** [comment]
Got it.
I get on with this.

**Comment by KasparTr** [comment]
Is this issue closed now, no more help needed? Asking cause it is opn in the "whishlist". 
Would be clad to help out with any feature requests or issues.

**Comment by intelliot** [comment]
Help is welcome. Thanks!
